config/routes.rb
Rails.application.routes.draw do

  root 'urls#new'
  resources :urls do
    get 'url_shortener_api', :on => :collection
    post 'url_shortener_api', :on => :collection
  end

end

app/models/url.rb
class Url < ActiveRecord::Base
    require 'digest'
    before_save :create_short_url

    BAD_WORDS = ['shit', 'fuck', 'damn', 'bitch', 'ass']

    def self.search(search)
      search2 = search.to_s.gsub '0', 'O'
      if search
        where('long_url LIKE ? OR short_url LIKE ?', "%#{search}%", "%#{search2}%")
      else
        where(nil)
      end
    end

    protected

    def check_diff(a, b)
        cnt = 0
        (0..(a.length)).each do |i|
           cnt = cnt+1 if a[i] != b[i]
        end
        return cnt
    end

    def check_all_short_urls(shrt)
        Url.all.each do |url|
            if check_diff(shrt, url.short_url) <= 1
                return false
            end
        end
    end

    def create_short_url
        short = Digest::MD5.hexdigest(self.long_url+"a shortening salt").slice(0..6)
        short.gsub '0', 'O'

        # Recalculate short url in case a duplicate is found or a curse word is found
        if ( (check_all_short_urls(short) == false) || (BAD_WORDS.include? short.downcase) )
            self.long_url = self.long_url + '_'
            create_short_url
        else
            self.short_url = short
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
    @urls= Url.all.search(params[:search]) unless params[:id ]# So that urls#index can show all urls created
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def url_shortener_api
    unless request.method == "POST"
        render text: "Please call this API using an HTTP POST request", status: :unprocessable_entity and return
    end

    errors = Array.new
    warnings = Array.new

    # url not present
    unless params["url"].present?
        errors << "URL is required, but not present."
        render text: errors.join(" \n"), status: :unprocessable_entity and return
    end

    # url is short and needs to be parsed
    if params[:url].length > 7 && params[:url].index('tny/')
      tmp_shrt_url = params[:url]
      tmp_shrt_url = tmp_shrt_url[tmp_shrt_url.index('tny/')+4,tmp_shrt_url.length]
      params[:url] = tmp_shrt_url
    end

    # found short url
    if Url.find_by_short_url(params[:url])
      warnings << 'The corresponding long url is: ' + Url.find_by_short_url(params[:url]).long_url
    else
      # Create long URL
      new_url = Url.new(long_url: params[:url])

      if new_url.save
        warnings << 'Short url created is: tny/' + new_url.short_url
      else
        errors << 'Unable to create url'
      end
    end

    if !Url.find_by_short_url(params[:url]) && !Url.find_by_long_url(params[:url])
      errors << 'The url provided came back without results, please try again.'
    end

    unless errors.empty?
        render text: errors.join(" \n"), status: :unprocessable_entity and return
    end

    render :text => warnings.join("\n"), :status => 200

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:long_url, :short_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "container">
  <%= yield %>
</div>

</body>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url, :style => 'float:left') do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="field">
    <%= f.text_field :long_url, placeholder: 'Long URL' , class: 'form-control' %>
  </span>
  <span class="actions">
    <%= f.submit 'Shorten URL', class: "btn btn-default",  style: "margin: 0px 3px 10px 10px;"  %>
  </span>
<% end %>

<%= form_tag @urls_path, :method => 'get', :style => "clear:right", :id => "users_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] , placeholder: 'Search', class: 'form-control' , style: 'margin-top: 13px;'%>
    <%= submit_tag "Search", :name => nil, class: "btn btn-default", style: "margin: 12px 3px 0px 10px;" %>
  </p>
<% end %>

<br/><br/><br/>

<div class="table-responsive">
<table id='urls_table' class="table table-striped table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Long url</th>
      <th>Short url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr data-id="<%=url.id%>" data-time="<%=url.created_at.to_i%>">
        <td><%= url.long_url %></td>
        <td><%= 'tny/' + url.short_url %></td>
        <td><%= link_to 'Details', url %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="field">
    <%= f.text_field :long_url, placeholder: 'Long URL' %>
  </span>
  <span class="actions">
    <%= f.submit 'Shorten URL', style: "margin: 2px 3px 0px 10px;" %>
  </span>
<% end %>

<br/>
<br/>
<%= link_to 'Show', @url %> |
<%= link_to 'Back', new_url_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Urls</h1>

<table>
  <thead>
    <tr>
      <th>Long url</th>
      <th>Short url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.long_url %></td>
        <td><%= 'tny/' + url.short_url %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>Url Shortener</h1>

<%= render 'form' %>

<%#= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Long url:</strong>
  <%= @url.long_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= 'tny/' +  @url.short_url %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', new_url_path %>